// The try statement defines a code block to run (to try).

// The catch statement defines a code block to handle any error.

// The finally statement defines a code block to run regardless of the result.

// The throw statement defines a custom error.
try {
  consol.log("hello This error is generated by me");
} catch (error) {
  console.log("error", error.message);
}

// start from eval error
// An EvalError indicates an error in the eval() function.

// Range Error
// A RangeError is thrown if you use a number that is outside the range of legal values.

// Reference Error
// A ReferenceError is thrown if you use (reference) a variable that has not been declared:

// Syntax Error
// A SyntaxError is thrown if you try to evaluate code with a syntax error.

// Type Error
// A TypeError is thrown if you use a value that is outside the range of expected types:

// num.toUpperCase();   // You cannot convert a number to upper case

// URI (Uniform Resource Identifier) Error
// A URIError is thrown if you use illegal characters in a URI function:
